version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/commdb
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - comm-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - comm-network

networks:
  comm-network:
    driver: bridge

volumes:
  mongodb_data:
